import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'
import Home from './index.jsx'
import About from './about.jsx'
import Account_settings from './user-account-settings.jsx'
import Blog_details from './blog-details.jsx'
import Blog from './blog.jsx'
import Booking_payment from './booking-payment.jsx'
import Booking_success from './booking-success.jsx'
import Categories from './categories.jsx'
import Contactus from './contactus.jsx'
import Create_services from './create-service.jsx'
import Provider_customer_list from './provider-customer-list.jsx'
import Favorite from './user-favourites.jsx'
import Login from './login.jsx'
import Otp from './otp.jsx'
import Provider_accounts_settings from './provider-accounts-settings.jsx'
import Provider_booking from './provider-booking.jsx'
import Provider_coupons from './provider-coupons.jsx'
import Provider_dashboard from './provider-dashboard.jsx'
import Provider_earnings from './provider-earnings.jsx'
import Provider_holiday from './provider-holiday.jsx'
import Provider_offers from './provider-offers.jsx'
import Provider_payout from './provider-payout.jsx'
import Provider_review from './provider-review.jsx'
import Provider_security_setting from './provider-security-settings.jsx'
import Provider_services from './provider-services.jsx'
import Provider_social_profile from './provider-social-profile.jsx'
import Provuder_enquiry from './provider-enquiry.jsx'
import Provider from './providers.jsx'
import Register from './register.jsx'
import Reset_password from './reset-password.jsx'
import Service_details from './service-details.jsx'
import Service from './service.jsx'
import Provider_staff_list from './provider-staff-list.jsx'
import User_booking from './user-booking.jsx'
import User_booking_list from './user-booking-list.jsx'
import User_dashboard from './user-dashboard.jsx'
import User_reviews from './user-reviews.jsx'
import User_wallet from './user-wallet.jsx'
import { BrowserRouter } from 'react-router-dom'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <BrowserRouter>
    <App />
    </BrowserRouter>
  </StrictMode>,
)
